Implement anime table
saritasa-nest/camp-js-2022-andrey-alekseev pull request #1
Opened 2022-06-30 03:33 UTC by aletor123

Task: JC19-328

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa requested changes

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
> +  --base-low-opacity-color: rgb(92 131 165 / 30%);
Please be consistent with you color, choose hex or rgb. 

Also I suggest renaming `--base-low-opacity-color` into `--base-color-low-opacity`. It is not grammatically correct, but it semantically better.

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +    <h5 id="anime-table-desc">Here you can see anime</h5>
For level 5 heading, there should be other 4 level headings.
You should use html tags depending on their semantic meaning. You can change styles with css.

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/index.ts
> +}
If you have "and" in function description consider decomposing it into two. Ideally function should one thing at a time. Maybe write something like that.
```js
const table = fetchTable(1)
updateTable(table)
```

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/index.ts
> +  const tableBody = document.querySelector('.anime-table__body') as Element;
FYI, `document.querySelector` have a generic.
```suggestion
  const tableBody = document.querySelector<Element>('.anime-table__body');
```

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/pagination.ts
> +      target.closest(`.${PAGINATION_PREV_LINK_CLASS}:not(.${PAGINATION_DISABLED_CLASS})`)) {
Please, move `) {` to the new line

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/pagination.ts
> +      const page: number = parseInt(target.innerText, 10);
You should omit type annotation here, because it will be automatically inherited with `parseInt` return type

2022-06-30 04:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/sorting.ts
> +  const isAsc = sortedColumn.classList.contains(
[Avoid contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-06-30 04:43 UTC, golovachev-yaroslav requested changes

2022-06-30 04:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +  font-family: "Material Icons", sans-serif;
It would be better to use var, example: `var(--material-icons-font)`

2022-06-30 04:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +        <a class="dropdown-trigger" data-target="navbar-account-dropdown">
`a` without `href` looks strange, the tag `a` is an anchor tag that navigates to another page or section on a page. I think you can use tag button here.

2022-06-30 04:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    <a class="pagination-block__link"><em class="material-icons">chevron_left</em></a>
The same with the button. Please check others.

2022-06-30 05:43 UTC, maxineo commented on apps/vanilla/src/pages/scripts/sorting.ts
> +    if (alreadySorted) {
Please add a [prefix](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#prefixes)

2022-06-30 05:43 UTC, maxineo commented on libs/core/models/sortOptions.ts
> +}
Please give each enum member a string value.

2022-06-30 06:03 UTC, panov-aleksey-saritasa requested changes

2022-06-30 07:00 UTC, aletor123 commented on libs/core/models/limitOffsetPagination.ts
> +}
In future we will implement Cursor pagination, so I decided to add this prefix

2022-06-30 07:36 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/index.ts
> +}
I'll rename it, but this function uses in several places and i think it will be better to store fetch and render in one function

2022-06-30 08:26 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/scripts/index.ts
> +  renderTable(1);
```suggestion
  renderTable();
```

2022-06-30 10:07 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  ) as Element;
Please use generic here

2022-06-30 10:08 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/scripts/sorting.ts
> +    const currentOrderColumn = tableHeader.querySelector(
Same with generic. Please revise every query selector. With it you can omit validation 
```ts
    if (!(target instanceof HTMLElement)) {
      return;
    }
```

2022-06-30 10:10 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/scripts/index.ts
> +  }
Same with `for` use `forEach` instead

2022-07-01 03:13 UTC, golovachev-yaroslav approved these changes

2022-07-01 04:20 UTC, artem-sotnichenko-saritasa commented on libs/core/models/anime/animeListItem.ts
> + * AnimeListItem.
You should remove duplication of class name in your jsdoc. Just `Model for representing anime in list.` is good

2022-07-01 04:20 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/api/services/animeService.ts
>     * */
Please be consistent with your jsdoc. I seen properly formatted jsdoc in your code (mappers), do it everywhere please.
Your multiline jsdoc should look like this. Single space after `*`, close comment with just `*/`
```js
/**
 * Some description.
 * @param name Param description.
 */
```

2022-07-01 06:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <div class="anime-table-wrapper">
Do you need this tag?  I mean `container` is already handling table-related layout

2022-07-01 06:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/index.ts
> +  tableRow.classList.add('anime-table-row');
I think there is no need to make separate block for `anime-table-row` element, since rows are part of table and usually table controls how its rows look like. You could name it `anime-table__row`

2022-07-01 06:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/pagination.ts
> + * */
Please, change docs

2022-07-01 06:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  const currPage = (paginateOptions.offset / ITEMS_PER_PAGE) + 1;
Please, [avoid contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-07-01 10:14 UTC, elena-dragunova approved these changes

2022-07-01 14:29 UTC, chernodub requested changes

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    <button class="pagination-block__link"><em class="material-icons">chevron_right</em></button>
It would be easier to handle disabled state if you prefer native `disabled` attribute for the buttons. The browser won't emit `click` event then, and you will be able to remove the <code>target.closest(`.${PAGINATION_NEXT_LINK_CLASS}:not(.${PAGINATION_DISABLED_CLASS}`)</code> handling. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    nextLink.classList.add(PAGINATION_DISABLED_CLASS);
This is very hard to comprehend why part of the classes is applied to `li` and part to the `button`, consider simplifying the amount of elements managed in your javascript

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    <button class="pagination-block__link"><em class="material-icons">chevron_right</em></button>
Prefer using named constant that you defined in the beginning of the file for `pagination-block__link`

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> + *  @param page Pagination page.
Sounds tautological :)

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> + *  Get formatted pagination link.
What does "formatted" mean in this context? :)

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  return pages;
Please consider revising this logic, it is very hard to understand what's happening here :)

2022-07-01 14:29 UTC, chernodub commented on apps/vanilla/src/pages/scripts/sorting.ts
> +const SORTED_CLASS = 'anime-table__header-column_sort';
What is the difference between these two classes exactly? Can you use one? If no, please consider revising the name/docs

2022-07-02 08:11 UTC, pavel-romanov8 requested changes

2022-07-02 08:11 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +      target.closest(`.${PAGINATION_PREV_LINK_CLASS}:not(.${PAGINATION_DISABLED_CLASS})`)
Doesn't it strange that we perform some business logic (paginate) and render things based on styles? As for me, classes meant to style things and nothing more

2022-07-02 08:11 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> + *  @param paginateOptions Current paginate options.
```suggestion
 *  @param paginateOptions Current pagination options.
```

2022-07-02 08:11 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    'pagination-block__links',
Please, use constants that you declared above in order to sync all changes in case there will be any

2022-07-03 07:12 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  pages: number[],
How can i declare n-length tuple?

2022-07-03 07:12 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    'pagination',
Yes, this is materizlize class

2022-07-03 07:54 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    <button class="pagination-block__link"><em class="material-icons">chevron_right</em></button>
But i'm handling click on `pagination-wrapper`, and button has `em` tag inside that will handle click event. But yes current implementation is bad, i'll rewrite this

2022-07-03 08:45 UTC, aletor123 commented on apps/vanilla/api/services/animeService.ts
> +const url = 'anime/';
Why should i use URL object that forces me to use CONFIG.apiUrl as second parameter, that i've already added to axios `baseURL`?

2022-07-03 09:16 UTC, aletor123 commented on apps/vanilla/src/pages/index.html
> +    <ul id="navbar-account-dropdown" class="dropdown-content">
it's class from `materizlize`

2022-07-04 00:24 UTC, pavel-romanov8 commented on apps/vanilla/api/services/animeService.ts
> +const url = 'anime/';
Didn't notice that you are using axios lib. Then, it is fine

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/global/variables.css
> +  --base-color-low-opacity: rgb(92 131 165 / 30%);
There is no need to mention something about opacity in the name. It could be just `--base-color-light`. Check out the [section](https://wiki.saritasa.rocks/frontend/languages/css#naming) about naming in our wiki.

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/models/sortOptions.ts
> +export enum SortType {
It looks more like _direction_ rather than _type_

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/models/limitOffsetPagination.ts
> +/** Limit Offset pagination wrapper. */
```suggestion
/** Limit offset pagination wrapper. */
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/models/anime/animeShort.ts
> +export class AnimeShort extends Immerable {
I don't see any _AnimeLong_ or just _Anime_ models. So, what is the point of naming it like _short_ anime?

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/models/anime/animeShort.ts
> +/** Model for representing anime in list. */
There is no need to reference in our docs to some kind of list  since it might be used in some other places at some point of a time and the docs will be irrelevant

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/mappers/limitOffsetQuery.mapper.ts
> +    } as LimitOffsetQueryDto;
You already declared the return type of the function, so there is no need to cast it to `LimitOffsetQueryDto`

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/dtos/limitOffsetQuery.dto.ts
> +/** Limit Offset query DTO. */
```suggestion
/** Limit offset query DTO. */
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/dtos/limitOffsetQuery.dto.ts
> +/** Limit Offset query DTO. */
Please, be consistent with the naming. I see that here you are writing `DTO` in uppercase, but in some other places, like `LimitOffsetQueryMapper ` or `AnimeShortMapper` it is in lowercase

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/dtos/sortOption.dto.ts
> +  /** Ordering for api call. */
```suggestion
  /** Ordering for API call. */
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on libs/core/dtos/limitOffsetPagination.dto.ts
> +
Remove empty line

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/sorting.ts
> +const sortDirectionClassMap = {
Please, add type annotation for the map. In case there will be any new `SortType` typescript will notify us to change the place as well

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +        type="button"
Something wrong with identations here

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  const paginationLink = document.createElement('li');
As I see, it is not a link, but a list element. And it won't even contain any link in the future since you are inserting button, but not a link to it

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +        ${page.toString()}
I believe there is no need to call `toString` since you are using template strings anyway

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> + * @param pagesPerSide Num of pages on each side.
Avoid contractions
```suggestion
 * @param pagesPerSide Number of pages on each side.
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> + * @param pagesOnEnd Num of pages on each side.
Also, there is no difference between `pagesPerSide` and `pagesOnEnd`, so could we use just one? In case there is a difference, please document or properly

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +): Generator<number | string> {
Please, avoid such broad types, because it is really hard to work with them. Leave just `number` or `string`

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/vite-env.d.ts
> +  /** Api base url. */
```suggestion
  /** API base URL. */
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/vite-env.d.ts
> +  /** Api key for schema. */
```suggestion
  /** API key for schema. */
```

2022-07-04 00:58 UTC, pavel-romanov8 commented on apps/vanilla/src/utils/helpers.ts
> +export function* range(start: number, end: number): Generator<number> {
Is it hard to leave without python functions:smile:?

2022-07-04 01:15 UTC, pavel-romanov8 commented on libs/core/models/anime/animeShort.ts
> +export class AnimeShort extends Immerable {
In case there will be any of such models for card of specific anime, it would be better to call it like `AnimeBase` and extend `Anime` model with it, or, we could already create `Anime` model and just create `AnimeBase` from it, using utility types. With the second way, we are also avoiding confusions where we have something like _short_ model, but don't have any extended version of it

2022-07-04 01:53 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +): Generator<number | string> {
What if i need to return `...`

2022-07-04 01:54 UTC, aletor123 commented on apps/vanilla/src/utils/helpers.ts
> +export function* range(start: number, end: number): Generator<number> {
Yes, really)

2022-07-04 07:18 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/api/services/animeService.ts
> +  [AnimeSortField.Title]: 'title_eng,id',
I believe that API won't change much in the future, so we could reuse the enum and this map in Angular and React applications. With that in mind, I would recommend moving it to the `core` lib

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +    throw new Error('There isn\'t table body');
```suggestion
    throw new Error('There is no table body');
```

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +    throw new Error('There aren\'t table pagination block');
```suggestion
    throw new Error('There is no table pagination block');
```

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +  private static getTableRow(animeListItem: AnimeBase): HTMLTableRowElement {
You are not actually getting, but creating table row, let's rename to something like `createTableRow`

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +   * @param animeListItem Anime list item.
As you already rename `AnimeListItem` to `AnimeBase` let's rename the param as well

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +  private static getTableRow(animeListItem: AnimeBase): HTMLTableRowElement {
Why do we need it as `static` field? I see that you are using it only on line 91

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/scripts/index.ts
> +  private tablePaginator: Paginator;
As I see, you are not mutating class fields in any way. Let's mark them as read-only fields

2022-07-06 01:39 UTC, pavel-romanov8 commented on libs/core/models/sortOptions.ts
> +/** Sort type. */
Please, change the docs as well

2022-07-06 01:39 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/index.css
> +  height: 128px;
I'm not sure why the comment is not resolved. Please, let me know if you have any questions

2022-07-07 18:10 UTC, chernodub approved these changes
Good job!

2022-07-07 18:10 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +    this.paginationButtons.forEach(paginationButton => {
So it's not buttons after all, it's `li` items containing buttons. I'd recommend mentioning that in the name of the property in order to make it more explicit

2022-07-07 18:10 UTC, chernodub commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  private static *getPresentedPages(
I've never seen generators applied both in our camps or production, respect 🚀😄

2022-07-08 00:43 UTC, pavel-romanov8 approved these changes

2022-07-10 11:41 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/pagination.ts
> +  private paginationButtons: PaginationButton[];
I'm mutating this

2022-07-10 11:47 UTC, merged