Implement authentication #JC19-457
saritasa-nest/camp-js-2022-andrey-alekseev pull request #13
Opened 2022-08-18 06:34 UTC by aletor123

2022-08-18 08:06 UTC, timofei-maximov-saritasa requested changes

2022-08-18 08:06 UTC, timofei-maximov-saritasa commented on apps/react/src/utils/apiUrls.ts
> +}
Do you really need this as class?

2022-08-18 08:06 UTC, timofei-maximov-saritasa commented on libs/core/mappers/appError.mapper.ts
> +export class AppErrorMapper {
Please, be consistent with your mappers. You have `namespace` and `class` mappers. Select one approach.

2022-08-18 08:29 UTC, aletor123 commented on apps/react/src/features/auth/pages/LoginPage.tsx
> +    <div className='form-wrapper'>
What if these are global styles?

2022-08-18 15:34 UTC, timofei-maximov-saritasa commented on apps/react/src/components/Navbar/NavBar.tsx
> +            </>
You can you ternary operator here https://beta.reactjs.org/learn/conditional-rendering#conditional-ternary-operator--

2022-08-18 15:34 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/RegisterForm.tsx
> +      {formError !== null && <p className="text-danger">{formError}</p>}
You can use `Typography` component with `sx` property. `sx` to keep theme consistent across your app.
Also, you can use `Alert` component with built-in `error` variant

```tsx
<Typography
  sx={theme => ({
    color: theme.palette.error.main,
  })}
>
 ```
 
 Or you can use

2022-08-18 15:34 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/RegisterForm.tsx
> +        </Button>
Formatting issue

2022-08-18 15:34 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/RegisterPage.tsx
> +  <div className="form-wrapper">
I'm not sure that you should use global css for this. Actually, you can make standalone component. like `FormLayout` and use css modules  to get reduce duplicated code.

2022-08-18 15:54 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm.tsx
> +import { FC, memo, useEffect, useState } from 'react';
Put this component in folder with the same name as component's file name

2022-08-18 15:55 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/LoginPage.tsx
> +import { FC, memo } from 'react';
Same about folder

2022-08-18 15:55 UTC, timofei-maximov-saritasa commented on apps/react/src/components/PageLoader/PageLoader.tsx
> +import Backdrop from '@mui/material/Backdrop';
Don't forget to add `index.ts` file for re-exporting your components. Let's be consistent 😇

2022-08-22 01:37 UTC, timofei-maximov-saritasa approved these changes

2022-08-22 01:37 UTC, timofei-maximov-saritasa commented on apps/react/src/components/form/Form/Form.tsx
> +const FormComponent: FC<Props> = ({ children, ...props }: Props) => (
```suggestion
const FormComponent: FC<Props> = ({ children, ...props }) => (
```

2022-08-22 01:37 UTC, timofei-maximov-saritasa commented on apps/react/src/components/form/FormControls/FormControls.tsx
> +const FormControlsComponent: FC<Props> = ({ children, ...props }: Props) => (
```suggestion
const FormControlsComponent: FC<Props> = ({ children, ...props }) => (
```

2022-08-22 01:37 UTC, timofei-maximov-saritasa commented on apps/react/src/components/form/FormWrapper/FormWrapper.tsx
> +const FormWrapperComponent: FC<Props> = ({ children, ...props }: Props) => (
```suggestion
const FormWrapperComponent: FC<Props> = ({ children, ...props }) => (
```

2022-08-22 05:15 UTC, golovachev-yaroslav requested changes

2022-08-22 05:15 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +const RegisterValidationSchema = Yup.object().shape({
Let's move initial state and validation schema to the separate file(ex.: formSettings.js). It makes this code more clear and without overload.

2022-08-23 04:32 UTC, pavelzadorin-saritasa approved these changes

2022-08-23 04:40 UTC, merged