Implement anime list #JC19-466
saritasa-nest/camp-js-2022-andrey-alekseev pull request #16
Opened 2022-08-25 03:21 UTC by aletor123

2022-08-25 10:45 UTC, golovachev-yaroslav requested changes

2022-08-25 10:45 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeDetails/AnimeDetails.module.css
> +  background-color: #188798;
What about css var?

2022-08-25 10:45 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeDetails/AnimeDetails.tsx
> +          onClick={onImageClick}
Is it possible to set focus by tab key? 
Looks like missed here, please check
```
role="button"
tabIndex="0"
```

2022-08-26 10:36 UTC, golovachev-yaroslav approved these changes

2022-08-26 10:36 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/pages/AnimesPage/AnimesPage.tsx
> +  useLayoutEffect(() => {
Why did you change hook?

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/AnimeDetails/AnimeDetails.module.css
> +}
It's a bit dangerous to set colors in root like this from component. Over time you may face collisions. Lets set variable inside `.anime`

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/AnimeDetails/AnimeDetails.tsx
> +            <Typography className={style['anime__status__text']}>{anime.status}</Typography>
`anime__status__text` is violating BEM.

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/store/anime/selectors.ts
> +  (state: RootState) => selectAllStudios(state.studio),
Let's pass input selectors as array https://redux.js.org/usage/deriving-data-selectors#createselector-overview
Also, if I'm not mistaken, we can use write like `[selectAnimeBaseById, selectAnimeExtraById, selectAllGenres, selectAllStudios]`

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/store/animeBase/slice.ts
> +      state.listIds.push(...action.payload.items.map(animeBase => animeBase.id));
I'm not sure how immer will handle this. Are you sure that you will get a new state with `listIds`. If not, then you can assign new array to `listIds`. Perhaps, I'm overthinking.

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/store/animeBase/state.ts
> +  readonly listIds: EntityId[];
Missing readonly. If you will face issues with `immer`, then you can use `castDraft` from `immer`

2022-08-26 11:33 UTC, timofei-maximov-saritasa commented on apps/react/src/store/anime/selectors.ts
> +    } as Anime;
You can add return type to get rid of type-casting

2022-08-27 04:55 UTC, aletor123 commented on apps/react/src/features/anime/pages/AnimesPage/AnimesPage.tsx
> +  useLayoutEffect(() => {
Because layout was jerking because is_loading state of anime list is false by default

2022-08-27 08:17 UTC, aletor123 commented on apps/react/src/store/animeBase/slice.ts
> +      state.listIds.push(...action.payload.items.map(animeBase => animeBase.id));
`Are you sure that you will get a new state with listIds?`. Yes, i checked this

2022-08-27 08:24 UTC, aletor123 commented on apps/react/src/store/animeBase/slice.ts
> +      state.listIds.push(...action.payload.items.map(animeBase => animeBase.id));
![image](https://user-images.githubusercontent.com/75448378/187021946-ac1ef57d-22d1-42f1-b43e-4b18818fc0a9.png)

2022-08-29 08:00 UTC, closed without merging