Implement authentication
saritasa-nest/camp-js-2022-andrey-alekseev pull request #2
Opened 2022-07-04 04:42 UTC by aletor123

Task: JC19-337

2022-07-04 05:07 UTC, panov-aleksey-saritasa commented
@aletor123 please, update `linting.yml` for this branch too 🙂

2022-07-04 05:20 UTC, elena-dragunova requested changes

2022-07-04 05:20 UTC, elena-dragunova commented on apps/vanilla/src/global/components.css
> +  background-color: #5c83a5;
Please use variables for colors.

2022-07-04 05:20 UTC, elena-dragunova commented on apps/vanilla/src/pages/login/index.html
> +    <h4>Login into account</h4>
Avoid skipping heading levels: always start from 'h1', followed by 'h2' and so on.

2022-07-04 05:20 UTC, elena-dragunova commented on apps/vanilla/src/pages/login/index.html
> +    <form class="login-form" method="post">
If you don't set 'action' you don't need 'method' attribute.

2022-07-04 05:20 UTC, elena-dragunova commented on apps/vanilla/src/pages/register/index.html
> +    <h4>Create new account</h4>
Avoid skipping heading levels: always start from 'h1', followed by 'h2' and so on.

2022-07-04 06:55 UTC, golovachev-yaroslav approved these changes

2022-07-04 06:55 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/login/index.html
> +            ><i class="material-icons">arrow_back</i>Main page</a
Don't break closing `>`. It should be in one row with `<`

2022-07-04 08:13 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/base.css
> +}
Don't use float, now it considered smelly. Float should only be used to allow text to wrap around elements.
Prefer flexbox or grid instead.

2022-07-04 08:13 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +        <ul class="align-right">
You should use flex here instead of `align-right`.

2022-07-04 08:13 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/utils/passwordValidation.ts
> + * */
Please format jsdoc properly 😉

2022-07-04 08:13 UTC, artem-sotnichenko-saritasa commented on libs/theme/src/variables.css
> +  --success-color: #55c745;
Please be consistent, choose one: hex or color names.

2022-07-04 09:03 UTC, elena-dragunova approved these changes

2022-07-04 14:17 UTC, chernodub commented
@aletor123 please make sure you follow our conventions on commit subject https://wiki.saritasa.rocks/frontend/tools/git#commit-messages

2022-07-04 15:05 UTC, chernodub requested changes

2022-07-04 15:05 UTC, chernodub commented on apps/vanilla/src/pages/login/index.html
> +            <label for="password">Password</label>
To reduce nesting, you could wrap the input into label like the following (this would also allow you to avoid the need of `id`):
```html
<label class="input-field">
  <input />
</label>
```

2022-07-04 15:05 UTC, chernodub commented on apps/vanilla/src/pages/login/index.html
> +              id="password"
For better UX, please use autocomplete attributes https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2022-07-04 15:05 UTC, chernodub commented on apps/vanilla/src/pages/login/index.html
> +          <div class="row">
Instead of using mentally-deprecated `row`/`col` approach, please consider using CSS `grids`

2022-07-05 06:49 UTC, aletor123 commented on apps/vanilla/src/pages/register/index.html
> +              class="validate"
it's material class

2022-07-05 07:35 UTC, aletor123 commented on apps/vanilla/src/api/interceptors/schemaInterceptor.ts
> +      // eslint-disable-next-line @typescript-eslint/naming-convention
Now it's just one line, should i create this file?

2022-07-05 08:41 UTC, aletor123 commented on apps/vanilla/src/pages/login/index.html
> +            <label for="password">Password</label>
In this implementation materialize styles wont work

2022-07-05 08:50 UTC, aletor123 commented on apps/vanilla/src/pages/login/index.html
> +          <div class="row">
I'm using materialize

2022-07-05 09:49 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-05 09:49 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/utils/formProcessing.ts
> + * return boolean that shows if the form is valid.
Typo

2022-07-07 02:48 UTC, panov-aleksey-saritasa approved these changes

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/api/services/authService.ts
> +  export async function register(registrationForm: UserRegistrationForm): Promise<void> {
Services shouldn't know anything about such UI-related things as forms

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/register/index.html
> +        <div class="back-link">
Consider adding heading to the page.

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/register/index.html
> +        <div class="back-link">
If you don't want it on your page visually, you could use the following util class:

```css
.visually-hidden {
  clip: rect(0 0 0 0);
  clip-path: inset(100%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
  margin: 0;
}
```

You can read about it [here](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/)

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/login/login.ts
> +  }
Please, try not to use `!` when it's possible, in your case you could use De Morgan's law:
```suggestion
  if (validatePassword(passwordField.value) && validateEmail(emailField.value)) {
    return;
  }
```

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/login/login.ts
> +  }
And it seems that when all validations are correct, nothing happens. Is it intended?

2022-07-07 02:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/login/login.ts
> +    window.location.href = AppUrl.Base;
You could make some util function for navigation that would accept `AppUrl` as parameter

2022-07-07 12:56 UTC, aletor123 commented on apps/vanilla/src/api/services/authService.ts
> +  export async function register(registrationForm: UserRegistrationForm): Promise<void> {
Maybe name the name is confusing, but this Interface uses only to provide data form data to services. Should i rename it to `UserRegistrationFormData`?

2022-07-07 15:53 UTC, aletor123 commented on apps/vanilla/src/api/services/authService.ts
> +  export async function register(registrationForm: UserRegistrationForm): Promise<void> {
Or maybe `UserRegistrationData`?

2022-07-07 19:15 UTC, timofei-maximov-saritasa approved these changes

2022-07-07 19:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/utils/navigation.ts
> +export function moveToPage(appUrl: AppUrl): void {
I would suggest to rename this function to `redirect`

2022-07-07 19:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/api/services/storageService.ts
> +export namespace storageService {
```suggestion
export namespace StorageService {
```

2022-07-07 19:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/register/register.ts
> +    if (emailError) {
Please, [avoid implicit type casting](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting)

2022-07-07 19:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/utils/query.ts
> +export function getElementOrRaiseError<T extends Element>(query: string): T {
`query` -> `selector`

2022-07-07 19:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/utils/query.ts
> +export function getElementOrRaiseError<T extends Element>(query: string): T {
Great approach! 🔥

2022-07-08 11:36 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/api/services/authService.ts
> +  export async function register(registrationForm: UserRegistrationForm): Promise<void> {
I think `UserRegistrationData` is name. You could even reduce it to `RegistrationData`

2022-07-13 13:57 UTC, merged