Filter by anime type  #JC19-363
saritasa-nest/camp-js-2022-andrey-alekseev pull request #3
Opened 2022-07-13 16:30 UTC by aletor123

2022-07-14 02:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +          <label>Type</label>
You should associate `<select>` with `<label>`
Check out https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label for details

2022-07-14 02:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/api/services/animeService.ts
> +    );
```suggestion
    const filterParams = FilterOptionMap.toDto(
      filterOptions,
    );
```

2022-07-14 02:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/filtering.ts
> +    filtersChangedCallback: Function,
`filtersChangedCallback` is already declared on 43 line, so there is no need to use [parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties)

2022-07-14 02:31 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  public readonly filtersChangedCallback: Function;
Please, avoid using `Function` type, it means literally any function with any signature. In your case you code narrow it to `() => void`. Or even create type alias for callbacks:
```ts
type Callback = () => void;
```

2022-07-14 02:31 UTC, panov-aleksey-saritasa commented on libs/core/models/filterOption.ts
> +  IContains = 'iContains',
What does `I` prefix mean?

2022-07-14 02:57 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-14 02:57 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/api/services/animeService.ts
> +    filterOptions: FilterOption<AnimeFilterField>[],
Don't forget about readonly for arrays

2022-07-14 04:27 UTC, aletor123 commented on libs/core/models/filterOption.ts
> +  IContains = 'iContains',
Case insensetive

2022-07-14 06:31 UTC, timofei-maximov-saritasa approved these changes

2022-07-14 06:31 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/scripts/filtering.ts
> +   * @param value - Field value.
```suggestion
   * @param filterField Field to sort.
   * @param value Field value.
```

2022-07-14 06:31 UTC, timofei-maximov-saritasa commented on libs/core/models/filterOption.ts
> +  IContains = 'iContains',
Let's come up with better name, then.

2022-07-15 07:35 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/filtering.ts
> +    filtersChangedCallback: Function,
My bad, sorry

2022-07-15 07:37 UTC, panov-aleksey-saritasa approved these changes

2022-07-15 19:18 UTC, dbitkovski requested changes

2022-07-15 19:18 UTC, dbitkovski commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  public readonly filtersChangedCallback: Callback;
It might be `private` as well

2022-07-15 19:18 UTC, dbitkovski commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  public filterOptions: FilterOption<AnimeFilterField>[];
I'd prefer to add a `get` property for this field sinсe you can't mark it with `readonly`

2022-07-15 19:18 UTC, dbitkovski commented on apps/vanilla/src/pages/scripts/types.ts
> +export type Callback = () => void;
@aletor123 @panov-aleksey-saritasa don't you think `Callback` is too abstract name? You're right, callback functions suppose to have `void` as return type but they also might have parameters. In this case we propose that any callback has no params

2022-07-16 07:02 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/types.ts
> +export type Callback = () => void;
Yeah, I agree, callbacks could definitely have arguments. Didn't give it much thought, my bad

2022-07-18 13:45 UTC, chernodub approved these changes

2022-07-18 13:45 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +          <label for="types-select">Type</label>
Not sure if I mentioned this already, but, to avoid specifying ids and intermediate containers (like `.filters__types`), you could wrap your control elements into label:
```html
<label for="filter">
  <span class="filter__label">Type</span>
  <select class="filter__control">
        <option value="" selected>Select Type</option>
    </select>
</label>
```

2022-07-18 13:45 UTC, chernodub commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  for (const [value, text] of Object.entries(animeTypeOptionsMap)) {
Usually, we prefer `label`/`value` convention for such things

2022-07-18 13:45 UTC, chernodub commented on apps/vanilla/src/pages/scripts/filtering.ts
> +    filtersChangedCallback: TableUpdateCallback,
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-shorthand-for-initializing-ordered-properties

2022-07-18 13:45 UTC, chernodub commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  private handleTypeSelected(): void {
Consider preferring `on` prefix for callbacks in future https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#on

2022-07-18 13:45 UTC, chernodub commented on apps/vanilla/src/pages/scripts/filtering.ts
> +  private _filterOptions: FilterOption<AnimeFilterField>[];
If you're not going to mutate the array, please consider making it an immutable tuple. [Promote immutability](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability)

2022-07-18 16:32 UTC, merged