Feature/js19 374 add searching
saritasa-nest/camp-js-2022-andrey-alekseev pull request #4
Opened 2022-07-15 06:46 UTC by EldrAbdr

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public btnClickCallBack: Function;
Please, avoid using `Function` type, it means literally any function with any signature. In your case you could narrow it to `() => void`. Or even create type alias for callbacks:
```ts
type Callback = () => void;
```

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public submitBtn: Element;
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public submitBtn: Element;
I suppose it should be `HTMLButtonElement`, not `Element`, right?

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public constructor(inputSelector: string, btnSelector: string, btnClickCallback: Function) {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-ordered-params-in-constructorsfunctions

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +        <button class="searching__button">Search</button>
Please, add `type` attribute to the button

2022-07-15 07:46 UTC, panov-aleksey-saritasa commented on libs/core/mappers/limitOffsetQuery.mapper.ts
> +    const search = searchString;
Unneeded `const search`, you could just pass `search: searchString` right away

2022-07-16 08:43 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-16 08:43 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public inputLine: HTMLInputElement;
I think line word is misleading, `inputElement` or just `input` would be better.

2022-07-16 09:59 UTC, aletor123 requested changes

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/index.css
> +  border-radius: 6px;
Redundant border-radius

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/index.html
> +      <div class="searching">
wrap this into `filters` block, because i'll also add filter by type in this block

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/index.html
> +      <div class="searching">
Use `flex` for this block

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/index.css
> +.searching__button {
just add class `btn` to button to apply materizlize styles

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/index.css
> +  margin: 0;
can be removed, because not it doesn't changing anything

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public submitBtn: Element;
I think all attrs can be private and readonly

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public constructor(inputSelector: string, btnSelector: string, btnClickCallback: Function) {
I think you don't need to provide selectors in constructors, because this class is create to work with search for anime table, so it can store selectors by itself

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public getInputLineContent(): string | null {
How it can be `null`? I think it's always string

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +      this.btnClickCallBack(this.getInputLineContent());
your callback doesn't expecting attributes

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/index.ts
> +        this.renderTable();
`resetPagination` will call this, see callback for `SortingProcessor`

2022-07-16 09:59 UTC, aletor123 commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +  public getInputLineContent(): string | null {
Maybe call it `getSearchString`?

2022-07-21 18:46 UTC, timofei-maximov-saritasa approved these changes

2022-07-21 18:46 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/scripts/animeSearch.ts
> +    this.submitButton.addEventListener('click', evt => {
Please, [avoid contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-08-29 08:00 UTC, closed without merging