Implement table management
saritasa-nest/camp-js-2022-andrey-alekseev pull request #8
Opened 2022-07-27 13:58 UTC by aletor123

…agement

# Conflicts:
#	apps/angular/src/app/features/anime/table/anime-table.component.html
#	apps/angular/src/app/features/anime/table/anime-table.component.ts
#	apps/angular/src/core/services/anime.service.ts

2022-07-31 09:37 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-31 09:37 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    this.listManager.pagePagination$.pipe(
Please try to avoid such amount of subscriptions. You can combine your filer / search / pagination / sorting into one `Observable` inside constructor to detect their changes, and then pipe it to fetch your anime list

2022-07-31 11:50 UTC, aletor123 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    this.listManager.pagePagination$.pipe(
I reduced number of subscriptions. I'm already combining all this parameters in ListManager that can be reused in other places where pagination is needed

2022-08-06 08:18 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-08 10:20 UTC, aletor123 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    this.listManager = new ListManager(this.initialParams);
I removed queryParams$ but list manager initialized in constructor because i need to take initial parameters from query

2022-08-08 10:22 UTC, aletor123 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    const { sortOptions, filtersOptions } = this.getParamsFromQuery(this.activeRoute.snapshot.queryParamMap);
I'm doing it in `ngAfterViewInit` because i need to access  `tableSort` that is child component. And it's initialized only in `ngAfterViewInit`

2022-08-09 03:59 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-09 03:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +interface AnimeFiltersType {
We usually add suffix `FormData` for form type name, i.e. `AnimeFiltersFormData`

2022-08-09 09:16 UTC, timofei-maximov-saritasa approved these changes

2022-08-09 09:16 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +        if (types !== null && types !== undefined) {
FYI, you can use `types != null` for `types: null | undefined`

2022-08-09 10:54 UTC, pavel-romanov8 requested changes

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +  [key: string]: string;
You can use `Record<string, string>` for that instead of creating a separate interface

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +  ORDERING_DIRECTION = 'orderingDirection',
Not sure why we are using snake case here

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +  @ViewChild(MatSort) private tableSort?: MatSort;
We usually place a field under decorator like so:
```suggestion
  @ViewChild(MatSort)
  private tableSort?: MatSort;
```

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    ).subscribe(
This configuration of `subscribe` already marked as deprecated in latest versions of RxJS. Instead, please, use it like so:
```ts
subscribe({
  next: () => {}
})
```

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +        const search = filterValues[AnimeFilterOptions.Search];
We are usually prefer to put side effects into `tap` operator. That way we are making them more explicit

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/core/rxjs/withIsFirst.ts
> +  let isFirst = true;
It looks like we are trying to introduce imperative style into declarative Rx. Instead of doing so, try to change the stream flow

2022-08-09 10:54 UTC, pavel-romanov8 commented on libs/core/models/anime/animeType.ts
> +  [AnimeType.Unknown]: AnimeType.toReadable(AnimeType.Unknown),
Please, create a pipe for that, instead of such dictionary

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/table.ts
> +    direction: <SortDirection>sort.direction,
You are not converting, but casting it

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/list-manager.ts
> +  private readonly pagination$ = new BehaviorSubject(new PaginationData());
If you are proving generics for other subjects let's provide one for this one as well

2022-08-09 10:54 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/list-manager.ts
> +  filtersOptions?: readonly FilterOption<TItemFilterFields>[];
Are they mutable?

2022-08-10 10:03 UTC, dbitkovski approved these changes

2022-08-12 02:27 UTC, pavel-romanov8 requested changes

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +        const queryParams: Record<string, string> = {
I believe that we can use `TableQueryParams` as a key for the record instead of plain string

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +        queryParams[TableQueryParams.OrderingDirection] = sortOptions !== null ? sortOptions.direction : '';
Not sure why we can initialize it directly in `queryParams` variable

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      page.pageIndex + 1,
By adding `+1` we are showing that the function knows something about the `PaginationData` inner implementation and because of that adding this +1 in order to make it works properly. Let's move this responsibility from the component to a class itself

2022-08-12 02:27 UTC, pavel-romanov8 commented on libs/core/pagination.ts
> +export class PaginationData {
Not sure that `Data` brings much value here. We can omit it and name the class like _Pagination_

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      (this.tableSort.sortables.get(sortOptions.field) as MatSortHeader)._setAnimationTransitionState(
Please, avoid usage of methods that starts with lower-dash because they are meant for internal usage. It is a common agreement in JS community

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/queryParameters.ts
> +export function getNumberQueryParameter(paramsMap: ParamMap, key: string): number | undefined {
Don't you think that we are having too many functionalities as _util_?

2022-08-12 02:27 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/list-manager.ts
> +export type ApiRequestCallback<TItem, TItemSortFields, TItemFilterFields> = (
Looks like `ListManageer` is more about UI layer. If that is the case, we shouldn't use any terms from repository layer because it is a leak of abstraction. You can check the architecture of our apps in wiki in order to have a common understanding of what we are trying to achieve - https://wiki.saritasa.rocks/frontend/frameworks/architecture/

2022-08-12 06:55 UTC, chernodub requested changes

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    }
Please consider reverting the conditions to remove the unnecessary indents and make the code more readable

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +        }
This switchcase-like logic makes me think if we even need the generalization of filters, then? Can we just have a single object representing the whole filter? something like:

```ts
interface PaginationQuery {
  searchString: string;
  type: AnimeType[];
  page: number;
  pageSize: number;
  // ...
}
```

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      filtersOptions,
After all, for me, it seems like you tried to generalize the filter params too much. Having an array of different filters won't bring much benefit, but instead (1) makes the code too hard to understand and (2) introduce some switchcase-like logic. I'd recommend simplifying it with some simple interface representing a query, like I suggested before.

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/services/anime.service.ts
> +      filterParams = FilterOptionMap.toDto(filterOptions);
I'd recommend to make the name more explicit `FilterOptionMap` -> `FilterOptionMapper`

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +    ]
We usually try not to use tuples in such context. This promotes other devs to decrease the readability of the code, since they basically have to give the names for the properties themselves, consider the following:
```ts
this.paginationResetParams$.pipe(
	map(([s, f]) => {...}),
);
```

Also, refactoring such thing would be a mess. E.g. for some reason, you'll need to change the order of these items, you'll have to refactor every place where it's used (rename the parameters).

tldr: please prefer objects over tuples to pass data. This approach makes your code more expressive

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +    }
Instead of triggering subject multiple times (with initial value and then second initial in the constructor), prefer intializing it inline with the argument passed in constructor. This would reduce the cognitive complexity in your code

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +    }
e.g:
```ts
this.sort$ = new BehaviorSubject(sortOptions ?? null)
``

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +      ),
Please prefer moving it into constants instead of initializing such stuff inline. This would increase the readability of your code. Also, you can move the intiailization into functions, to make constructor more expressive

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +        skip(1),
Usually, skipping value looks workaround-ish. For this case, I don't get why you're doing it. Please prefer either omitting such stuff from your code, or leaving a comment explaining why the first value is skipped. Because, for me, if observable called `resetParams$` it should reset params **every time** it emits.

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +  public readonly pagePagination$: Observable<PaginationData>;
Seems tautological/non-representative, can we improve the name?

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +      }),
What's the point updating it second time if it's already changed in the first call of `updatePagination`? Seems like it's almost a hacky and implicit loop

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +      switchMapTo(this.paginationResetParams$),
Since you wait for both to be triggered, why not generalizing the logic into a single subject?

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +    ), true);
This call seems to be unreadable because of the second parameter. https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#how-to-pass-arguments-to-functionsmethods

2022-08-12 06:55 UTC, chernodub commented on libs/core/pagination.ts
> +  private defaultPageSize = 10;
1. Since it's never reassigned, prefer `readonly`
2. Since it's a constant, prefer making it module scoped and https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-convention

In general, please always try to reduce the complexity of your classes/interfaces

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/pagination.ts
> +}
I don't see it used anywhere in this PR. Also, this seems like a mapper from domain to DTO, probably it's not a good idea having this in utils folder

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/list-manager.ts
> +) => Observable<LimitOffsetPagination<TItem>>;
Like @pavel-romanov8  mentioned, it's not only about the name. Your BE-provided representation of pagination leaks too. When operating on domain layer, we basically want to abstract ourselves from `limit`/`offset` but only use `pageNumber` and `pageSize`

2022-08-12 06:55 UTC, chernodub commented on apps/angular/src/core/utils/queryParameters.ts
> +  return numberParam;
This could be reduced to

```suggestion
const value = parseInt(paramsMap.get(key), 10);
return isNaN(value) ? undefined : value;
```

2022-08-12 06:55 UTC, chernodub commented on libs/core/models/sortOptions.ts
> +  return Object.values(SortDirection).includes(sortDirection as SortDirection);
Same here with converting enum to array using `Object.values`, be careful and consider using library I recommended before

2022-08-12 06:55 UTC, chernodub commented on libs/core/pagination.ts
> +  }
Do we need this info on domain layer? I believe no, this should be isolated in the mapping to DTO representation

2022-08-12 06:55 UTC, chernodub commented on libs/core/pagination.ts
> +    this.page = page ?? 1;
Is your pagination 1-based? If so, consider mentioning this in the docs. I believe, usually devs expect 0-based, if they're not R-fans

2022-08-12 07:00 UTC, aletor123 commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      (this.tableSort.sortables.get(sortOptions.field) as MatSortHeader)._setAnimationTransitionState(
This need because of issue
https://github.com/angular/components/issues/10242

2022-08-12 07:01 UTC, aletor123 commented on apps/angular/src/core/utils/queryParameters.ts
> +export function getNumberQueryParameter(paramsMap: ParamMap, key: string): number | undefined {
I thinks it's okay to store reusable functions in utils

2022-08-12 08:24 UTC, aletor123 commented on apps/angular/src/core/utils/list-manager.ts
> +      }),
This need to set total count from response

2022-08-12 10:46 UTC, aletor123 commented on apps/angular/src/core/utils/list-manager.ts
> +      switchMapTo(this.paginationResetParams$),
Because this will trigger infinite reload because of updating pagination after response

2022-08-13 11:48 UTC, aletor123 commented on apps/angular/src/core/utils/list-manager.ts
> +      switchMapTo(this.paginationResetParams$),
This need because i'm updating pagination after response and this mustn't trigger in this situation

2022-08-15 10:22 UTC, chernodub approved these changes

2022-08-15 10:22 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      (this.tableSort.sortables.get(sortOptions.field) as MatSortHeader)._setAnimationTransitionState(
Probably you could initialize the value on template then? https://material.angular.io/components/sort/api#:~:text=The%20direction%20to%20set%20when%20an%20MatSortable%20is%20initially%20sorted.%20May%20be%20overridden%20by%20the%20MatSortable%27s%20sort%20start

2022-08-15 10:22 UTC, chernodub commented on apps/angular/src/core/services/anime.service.ts
> +            LimitOffsetPaginationMapper.mapPaginationToLimitOffsetOptions(pagination),
Why not call it inside `LimitOffsetQueryMapper` to fully abstract the mapping to dto?

2022-08-15 10:22 UTC, chernodub commented on apps/angular/src/app/features/anime/table/anime-table.component.ts
> +      withLatestFrom(this.listManager.paginationResetParams$),
`this.listManager.paginationResetParams$` seems like an observable that should be isolated inside `listManager`, because the name tells me that this observable emits when I need to reset pagination. But it seems that you're trying to sit on two chairs at the same time. I believe it would be a good idea to either simply expose `sortOptions$` and `filterOptions$` observables, or just rename the property

2022-08-16 03:26 UTC, merged